# Generated by Django 2.2 on 2021-07-14 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
